### ISSUE TITLE
Manifest should use Electron baseapp

### ISSUE THREAD

**Issue by barthalion** [flathub/com.axosoft.GitKraken#1]

**Comment by Lctrs** [comment]
Hi !

If I understand correctly your issue, you mean it should use `org.electronjs.Electron2.BaseApp` instead of `io.atom.electron.BaseApp` as base. Right ?

Sadly, it won't work as GitKraken is not compatible with Electron 2 as of today (I just tested it).

**Comment by barthalion** [comment]
Yeah, my bad. I thought we already have xkbfile and libsecret in the "old" base app but apparently not.
