### ISSUE TITLE
Unable to open/configure terminal from application

### ISSUE THREAD

**Issue by junglerobba** [flathub/com.axosoft.GitKraken#12]
Using File -> Open Terminal prompts to configure a default terminal, however the list of terminals is empty and using a custom command (e.g. gnome-terminal) does not work either. 
Is this a restriction with flatpaks? Because as far as i know gnome has a configuration for a default terminal. Also File -> Open in File Manager works and uses the default file manager

**Comment by Lctrs** [comment]
Thats' likely a flatpak limitation. Since it runs the applications in a sandbox, I think it can't see the installed applications outside the sandbox. I'll see if Flatpak provides a way to fix this.

Ping @nedrichards @TingPing. Any ideas ?

**Comment by Lctrs** [comment]
I just had the confirmation on IRC that it's not possible at this moment. It would require some code changes in GitKraken.

**Comment by TingPing** [comment]
A custom command could work, you need to run `flatpak run --talk-name=org.freedesktop.Flatpak com.axosoft.GitKraken` and then set the custom command to `flatpak-spawn --host gnome-terminal`.

**Comment by Lctrs** [comment]
@TingPing Should I add this `talk-name` to the list of `finish-args` ?

**Comment by AlexP11223** [comment]
Still not fixed :(

> you need to run `flatpak run --talk-name=org.freedesktop.Flatpak com.axosoft.GitKraken`

Seems to work without this now, just `flatpak-spawn --host gnome-terminal` in custom command.

**Comment by AlejandroAkbal** [comment]
Im running that command and it does not work :/

![Image](https://github.com/user-attachments/assets/63453c1a-a5ad-4315-9b5d-786315d73a8f)
