### ISSUE TITLE
2 display bugs on Linux Mint 19 - Ubuntu Bionic

### ISSUE THREAD

**Issue by Nightbr** [flathub/com.axosoft.GitKraken#13]
Hey, 
it seems I have 2 issues so far with Gitkraken install through flatpak (works correctly from official .deb).

1- There is no icon, in app bar
![image](https://user-images.githubusercontent.com/4228646/43044903-21ba413e-8daf-11e8-863b-e42f27d0437b.png)
2- The menu bar can't hide with alt and doesn't respect system theme
![image](https://user-images.githubusercontent.com/4228646/43044918-57820c48-8daf-11e8-82fb-a2987e113119.png)

That's all I have noticed so far. 

If you need any logs or other screenshots let me know!

Thanks for your help

**Comment by TingPing** [comment]
Theme will be fixed once the app moves to Electron 2.

**Comment by Lctrs** [comment]
@Nightbr #30 should have fixed the icon issue.

**Comment by Eonfge** [comment]
To add to this, the File Browser also doesn't respect theming:
![screenshot from 2019-02-28 11-17-55](https://user-images.githubusercontent.com/33983090/53559512-86669800-3b4a-11e9-801a-56cb0b05e3cd.png)

**Comment by Lctrs** [comment]
@Nightbr @Eonfge May you please test #31 and tell me if it fixes any of your issues ?

**Comment by Eonfge** [comment]
@Lctrs I must disappoint you, I downloaded the test package (thanks @flathubbot) and i ran it using the terminal, but I saw the same default theme instead of the dark theme.

![Screenshot from 2019-03-22 08-41-00](https://user-images.githubusercontent.com/33983090/54807706-5bb9bc00-4c7e-11e9-94d3-49d5a8859c8e.png)
_About the image. On the left, you see GitKraken, the File Browser started from GitKraken. On the right is a terminal showing you which version I started. In the background you see the Nautilus, adhering to the dark theme_

**Comment by Lctrs** [comment]
@Eonfge And if you run it with `flatpak run --env=DCONF_USER_CONFIG_DIR=.config/dconf --filesystem=xdg-run/dconf com.axosoft.GitKraken//test` ?

**Comment by Eonfge** [comment]
Nope, no cigar.

**Comment by Lctrs** [comment]
And with `flatpak run --env=DCONF_USER_CONFIG_DIR=.config/dconf --filesystem=~/.config/dconf:ro --filesystem=xdg-run/dconf com.axosoft.GitKraken//test` ?

**Comment by Eonfge** [comment]
@Lctrs Nope, this trial-and-error process isn't really producing much success. By contrast, Lollypop is also a Flatpak and that is using the Adawaita-dark theme.

**Comment by Lctrs** [comment]
Okay. Sorry to bother you with this and thanks for your feedback. I just wanted to quickly do this last test. I'm not on GNOME currently. I'll look further into it when I get back from work tonight. Thanks again.

**Comment by Eonfge** [comment]
@Lctrs No problem, just let me know if I can help you test again.

**Comment by Lctrs** [comment]
Theme will be respected if you install its flatpaked version (eg. [`org.gtk.Gtk3theme.Adwaita-dark`](https://github.com/flathub/org.gtk.Gtk3theme.Adwaita-dark). Flatpak seems to handle this automatically (at least on version `1.4.1`).

Can you confirm ?

**Comment by Eonfge** [comment]
@Lctrs Issue resolved. It seems that it works with GitKraken 6.0.0, running on Flatpak 1.2.4 and org.gtk.Gtk3theme.Adwaita-dark 3.22, on Ubuntu 19.04

**Comment by Lctrs** [comment]
Thanks @Eonfge ! Since all issues seem resolved, I'm closing this issue.
