### ISSUE TITLE
Signing with smartcard fails

### ISSUE THREAD

**Issue by dennisreimann** [flathub/com.axosoft.GitKraken#131]
I have a Yubikey, which holds my GPG key. When signing a git commit, since v8.3 it instantly fails with "Wrong PIN" -- I don't even get asked to enter the PIN like before, it simply fails right away.

**Comment by Lctrs** [comment]
Do you reproduce the issue with the one of the official packages ? If yes, it should be directly reported to Axosoft.

**Comment by dennisreimann** [comment]
When I download the official app it works, it only fails with the version loaded from the Pop!_OS shop.
