### ISSUE TITLE
git: 'remote-https' is not a git command. See 'git --help'.

### ISSUE THREAD

**Issue by autonomobil** [flathub/com.axosoft.GitKraken#138]
When wanting to commit with gitkraken installed via flatpak, the following error pops up: 

`git: 'remote-https' is not a git command. See 'git --help'.`

This seems to indicate a missing library:

- https://stackoverflow.com/questions/51366101/git-remote-https-is-not-a-git-command
- https://stackoverflow.com/questions/54632745/git-remote-ttps-is-not-a-git-command
- https://unix.stackexchange.com/questions/694507/git-clone-from-https-url-fails-says-its-remote-https-is-not-a-git-command-an

I'm quite new to flatpak, how can I add this library to the flatpak install? Somewhere here https://github.com/flathub/com.axosoft.GitKraken/blob/master/com.axosoft.GitKraken.json?

**Comment by Lctrs** [comment]
That's weird. I'm cloning from https without any problem and curl is definitively present in the Platform.

Anyway, with the addition of GitKraken Terminal, I was considering switching to the Sdk as runtime and stop importing git binaries from it. I think your issue achieves to convince me. I'll do some local tests before pushing the change.

**Comment by autonomobil** [comment]
ok, good to know. Then I'll wait for the changes

**Comment by Lctrs** [comment]
May you test #117 please ?
