### ISSUE TITLE
Raspberry Pi OS: gitkraken cannot execute binary file

### ISSUE THREAD

**Issue by jalapenopuzzle** [flathub/com.axosoft.GitKraken#168]
pi@raspberrypi:~ $ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
pi@raspberrypi:~ $ flatpak install flathub com.axosoft.GitKraken
Looking for matches…

com.axosoft.GitKraken permissions:
    ipc       network       pcsc                  pulseaudio           ssh-auth
    x11       dri           file access [1]       dbus access [2]      tags [3]

    [1] /media, /mnt, /run/media, home, xdg-run/gvfs, xdg-run/gvfsd
    [2] org.freedesktop.Notifications, org.freedesktop.secrets, org.gtk.vfs.*
    [3] proprietary

        ID                            Branch         Op         Remote         Download
 1. [✓] com.axosoft.GitKraken         stable         i          flathub        96.8 MB / 95.6 MB

Installation complete.
pi@raspberrypi:~ $ flatpak run com.axosoft.GitKraken
**/app/extra/gitkraken/gitkraken: /app/extra/gitkraken/gitkraken: cannot execute binary file**
pi@raspberrypi:~ $ flatpak info com.axosoft.GitKraken

GitKraken - For repo management, in-app code editing & issue tracking.

          ID: com.axosoft.GitKraken
         Ref: app/com.axosoft.GitKraken/aarch64/stable
        Arch: aarch64
      Branch: stable
     Version: 8.10.3
     License: LicenseRef-proprietary
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 17.9 MB
     Runtime: org.freedesktop.Sdk/aarch64/22.08
         Sdk: org.freedesktop.Sdk/aarch64/22.08

      Commit: 6c9265f43aa9f090e4e504b2d14808be923357071508813f9f09211baf9d8e34
      Parent: 2a0baf8a997c3ceb75e3f4dbdac842c6376a28412a8b1e2e8c5f436a076cbcef
     Subject: Update krb5-1.20-final.tar.gz to 1.20.1-final (fc46ff0e)
        Date: 2022-11-17 07:16:15 +0000
pi@raspberrypi:~ $

**Comment by theofficialgman** [comment]
@Lctrs this is a HUGE no-no. you are packaging for aarch64, i386, and x86_64 and the deb you pull from is only x86_64

please only enabe x86_64 builds and remove the other builds with urgency

**Comment by theofficialgman** [comment]
@Lctrs you did not fix the issue fully
you need to have flatpak PURGE all aarch64 builds from the flathub repos otherwise it will still show up in appstores and allow installation

CC @flathub
