### ISSUE TITLE
Wrong URL for 4.0.3

### ISSUE THREAD

**Issue by WolfWalter** [flathub/com.axosoft.GitKraken#17]
Hi,
the URL for 4.0.3 is wrong. Have a look at [aur-commit](https://github.com/Azd325/gitkraken/commit/ec4b46287e6fe4d9bf88b8d889325f2f8947ef5a) for the correct URL.

**Comment by kepalas** [comment]
I'm getting the following error when updating:
```
Error: Failed to update com.axosoft.GitKraken/x86_64/stable: While downloading https://release.gitkraken.com/linux/v4.0.3.tar.gz: Server returned status 404: Not Found
```

**Comment by Lctrs** [comment]
*sigh*

Thanks for pointing me to the right URL.
