### ISSUE TITLE
Won't install

### ISSUE THREAD

**Issue by jlelse** [flathub/com.axosoft.GitKraken#2]
I can't install GitKraken due to the following error. I assume this is related to this build. It says an extra file has the wrong size.

![grafik](https://user-images.githubusercontent.com/8822316/41552744-f920770a-732f-11e8-80b0-20c88bfd4806.png)

**Comment by jlelse** [comment]
It is because the build is referencing a file that is changing and so is the sha256 key changing.

**Comment by jlelse** [comment]
The link should be like https://release.gitkraken.com/linux/v3.6.4.tar.gz

**Comment by jlelse** [comment]
I somehow still get this error. What might be wrong?

![grafik](https://user-images.githubusercontent.com/8822316/41555231-5d4e06f0-7337-11e8-8c39-9f765ca0157e.png)

**Comment by nedrichards** [comment]
I've pushed an updated archive size which matches what I see of the size and sha256.

**Comment by jlelse** [comment]
Forgot to update this :man_facepalming: I just notice, the version number in the appdata is also old..

**Comment by nedrichards** [comment]
I pushed a fix for that too. Works fine now.
