### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by proksi21** [flathub/com.axosoft.GitKraken#21]
Actions:

- flatpak install flathub com.axosoft.GitKraken

What should happen:

- Successful GitKraken installation

What actually happened:

- Exited with an error "Failed to install com.axosoft.GitKraken/x86_64/stable: While downloading https://release.gitkraken.com/linux/GitKraken-v4.0.4.tar.gz: Unacceptable TLS certificate"

**Comment by Lctrs** [comment]
Let me guess.

You're behind a proxy, probably in a corporate environment.

Sadly, this is beyond the scope of this wrapper.

I'm myself in such environment and I ended up installed the official `deb` package.

Before that, a little research on the Internet led to solutions such as trusting the CA certs of your proxy and things of the same acabit.

Gosh I hate corporate proxy.

Good luck !

I'm closing this now. I'll reopen it if you tell me my guess was wrong.

**Comment by agates** [comment]
I don't think this is a problem with corporate proxies.  I did check to work around ours, to be sure.

I it seems release.axocdn.com has a newer TLS cert as of September 19, 2018.  And the CA cert bundle on my machine (fedora here) is from February 24, 2018.  I'm not going to dig deeper, but I might have to wait for an update to my system ca-certificates.

**Comment by Lctrs** [comment]
If I remember correctly, I tried to install it before this date in my corporate environment, and I couldn't install it.

I'm not 100% sure it was the same error though.

Anyway, if I understand your answer correctly, I should not be able to install it on my personnal computer if my CA certs is outdated. Will try tonight.

**Comment by chintan-mishra** [comment]
Trying the same after running`update-ca-trust` command which updates CA-s on RHEL 6+ based system gives the same error.

**Comment by agates** [comment]
I'm getting the same problem on one of my personal ubuntu servers:

```
~$ curl https://release.gitkraken.com/linux/GitKraken-v4.0.5.tar.gz
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by proksi21** [comment]
Lctrs,

No, I'm not in a corporate environment. 
Under VPN, actually, but have the same problem without it.

**Comment by gcaguilar** [comment]
It was a Gitkraken error, but it's been solved.

**Comment by proksi21** [comment]
@Lctrs  Issue fixed
