### ISSUE TITLE
Unable to update git config: Git Error

### ISSUE THREAD

**Issue by chancock-arrowglobal** [flathub/com.axosoft.GitKraken#230]
Hi, might be similar to https://github.com/flathub/com.axosoft.GitKraken/issues/42 but error message is different and I'm on windows.

When I try to update profile I see:

![image](https://github.com/user-attachments/assets/2a27adf4-c095-42c9-b3d2-13bccd95a4c4)

The error logs show same:

```
[Tue Aug 27 2024 14:09:35 GMT+0100 (Irish Standard Time)] Unable to update git config: Git Error
[Tue Aug 27 2024 14:11:18 GMT+0100 (Irish Standard Time)] Unable to update git config: Git Error
[Tue Aug 27 2024 14:15:51 GMT+0100 (Irish Standard Time)] Unable to update git config: Git Error
[Tue Aug 27 2024 14:16:58 GMT+0100 (Irish Standard Time)] Unable to update git config: Git Error
```

No more detail than that.

My .gitconfig appears to have correct permissions, +rw for my user.

**Comment by Lctrs** [comment]
Hi !

This is the repo of the unofficial flatpak (a Linux packaging system) wrapper for GitKraken. We are not related to Axosoft (GitKraken's editor) at all. You can report this to their [Slack](https://gitkraken.slack.com/).
