### ISSUE TITLE
Missing screenshots

### ISSUE THREAD

**Issue by bilelmoussaoui** [flathub/com.axosoft.GitKraken#24]
https://flathub.org/apps/details/com.axosoft.GitKraken

**Comment by Lctrs** [comment]
Back when I created this flatpak, I searched for some in good quality and that actually match the style of the base gnome style but I couldn't find any.

If you find some, feel free to open a PR. :)

**Comment by Lctrs** [comment]
Or juste copy paste the links here and I'll do it.

**Comment by bilelmoussaoui** [comment]
I don't really use GitKraken at all. Just wanted to let you know that the screenshots are missing.
