### ISSUE TITLE
Can't edit profile & password in desktop client

### ISSUE THREAD

**Issue by ConnerAiken** [flathub/com.axosoft.GitKraken#26]
**Platform:** Windows 10 64-bit (10.0, Build 17134)
**Account Type:** Github SSO

Replication steps
1) Open gitkraken as admin or regular user
2) Click the profile icon in the top right
3) Click Profile & Password

Works fine w/o a github linked account.

**Comment by Lctrs** [comment]
Hi !

This is the repo of the unofficial flatpak wrapper for GitKraken. We are not related to Axosoft (GitKraken's editor) at all. You can report this to their [Slack](https://gitkraken.slack.com).
