### ISSUE TITLE
Icon issue in elementary OS Plank

### ISSUE THREAD

**Issue by peteruithoven** [flathub/com.axosoft.GitKraken#29]
On elementary OS Juno (Built on Ubuntu 18.04 LTS) Gitkraken's icon in Plank is replaced by icon not found icon while starting.  

## 1. When starting initially the correct icon is shown
![screenshot from 2019-01-30 20 39 23](https://user-images.githubusercontent.com/523210/52007731-6900c880-24cf-11e9-85ed-b107cd0c8e70.png)
## 2. Then when the loader appears a icon is not found icon is added beside the Gitkraken icon
![screenshot from 2019-01-30 20 37 27](https://user-images.githubusercontent.com/523210/52007769-7e75f280-24cf-11e9-8d8b-11e7e2e96793.png)
## 3. Then while the loader is still going the Gitkraken icon disappears
![screenshot from 2019-01-30 20 44 13](https://user-images.githubusercontent.com/523210/52007984-ee847880-24cf-11e9-9dc6-3b7fad829075.png)

Is this possibly an issue in the Flatpak layer?

I tried installing the deb from [their website](https://www.gitkraken.com/download) and that didn't have this issue:
![screenshot from 2019-01-30 20 51 37](https://user-images.githubusercontent.com/523210/52008496-07d9f480-24d1-11e9-9855-dd53f28fa631.png)

I'm running Flatpak 1.2.0.

Please let me know if I can provide more information.

**Comment by TingPing** [comment]
Desktop file probably needs to set `StartupWMClass`

**Comment by Lctrs** [comment]
Kudos for the very clear and detailed explanation 👍 

I won't have time to look at this until next week sadly. Feel free to provide a PR with the `StartupWMClass` entry in `gitkraken.desktop` as mentionned by @TingPing if you can't wait. :)

**Comment by TingPing** [comment]
If you run `xprop` and click on the window you will see its class.

**Comment by peteruithoven** [comment]
Thanks for the tips!

```
$ xprop WM_CLASS
WM_CLASS(STRING) = "gitkraken", "GitKraken"
```

[More Info on StartupWMClass](https://askubuntu.com/a/367851/519324)

**Comment by TingPing** [comment]
You can edit `/var/lib/flatpak/exports/share/applications/com.axosoft.GitKraken.desktop` or `~/.local/share/flatpak/exports/share/applications/com.axosoft.GitKraken.desktop` to include that line `StartupWMClass=gitkraken` and see if it fixes it.

**Comment by peteruithoven** [comment]
Ah! I didn't realize I could try that without rebuilding the flatpak.

I'm afraid that adding `StartupWMClass=GitKraken` or `StartupWMClass=gitkraken` to `/var/lib/flatpak/exports/share/applications/com.axosoft.GitKraken.desktop` didn't help. It did however have an impact in that it now consistently shows just the no icon found icon.

**Comment by TingPing** [comment]
>  It did however have an impact in that it now consistently shows just the no icon found icon.

Probably a good thing. I guess the window is perhaps setting its icon name and plank tries to use it. I'm not sure that can be solved.

**Comment by peteruithoven** [comment]
In case it's useful, the full xprops of GitKraken window
```
$ xprop
_NET_WM_ICON_GEOMETRY(CARDINAL) = 1487, 1080, 0, 0
_NET_WM_STATE(ATOM) = 
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_WM_DESKTOP(CARDINAL) = 0
_GTK_EDGE_CONSTRAINTS(CARDINAL) = 170
_NET_FRAME_EXTENTS(CARDINAL) = 0, 0, 66, 0
_NET_WM_ALLOWED_ACTIONS(ATOM) = _NET_WM_ACTION_MOVE, _NET_WM_ACTION_RESIZE, _NET_WM_ACTION_FULLSCREEN, _NET_WM_ACTION_MINIMIZE, _NET_WM_ACTION_SHADE, _NET_WM_ACTION_MAXIMIZE_HORZ, _NET_WM_ACTION_MAXIMIZE_VERT, _NET_WM_ACTION_CHANGE_DESKTOP, _NET_WM_ACTION_CLOSE, _NET_WM_ACTION_ABOVE, _NET_WM_ACTION_BELOW
_NET_WM_USER_TIME(CARDINAL) = 338054447
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: 669, 304
		program specified minimum size: 2048 by 1250
WM_NAME(UTF8_STRING) = "GitKraken"
_NET_WM_NAME(UTF8_STRING) = "GitKraken"
XdndAware(ATOM) = BITMAP
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x1, 0x0, 0x0
WM_WINDOW_ROLE(STRING) = "browser-window"
WM_CLASS(STRING) = "gitkraken", "GitKraken"
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_PID(CARDINAL) = 2
WM_LOCALE_NAME(STRING) = "en_US.UTF-8"
WM_CLIENT_MACHINE(STRING) = "xps"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, _NET_WM_PING
```

**Comment by peteruithoven** [comment]
After a restart I am suddenly seeing the correct logo all the time!
So adding `StartupWMClass=gitkraken` to `/var/lib/flatpak/exports/share/applications/com.axosoft.GitKraken.desktop` did help. I'll do a PR.
