### ISSUE TITLE
Git LFS was not found on your path

### ISSUE THREAD

**Issue by soliverr** [flathub/com.axosoft.GitKraken#33]
Hi.

I use GIT LFS with bitbucked.org. Every time i've got an error:
`This repository is configured for Git LFS but 'git-lfs' was not found on your path.`

You seted up git-lfs onto `/app/libexec/git-core` path. Would you please add this dir onto default app's PATH?

Thx

**Comment by Lctrs** [comment]
Thanks for reporting this issue. I'm not using `git-lfs` myself so this kind of things pass under the radar.

Can you test #34 once it has finished to build and tell me if it's working for you ? Thanks.

**Comment by soliverr** [comment]
Works like a charm :-) 
Thank you.

**Comment by Lctrs** [comment]
Thanks for your feedback. Fix has been merged. It should be available later this day.
