### ISSUE TITLE
Access to sftp and network locations

### ISSUE THREAD

**Issue by Eonfge** [flathub/com.axosoft.GitKraken#38]
I discovered that the Flatpak version of GitKraken is unable to open folders and repositories mounted through sftp. These directories do show up in Files, and you can access Network Locations if you're using the non-Flatpak version.

**Comment by Lctrs** [comment]
Hi @Eonfge,

Sorry for the late reply. Can you tell me which one of the following commands resolve your problem ?

1. `$ flatpak run --talk-name=org.gtk.vfs --talk-name=org.gtk.vfs.* com.axosoft.GitKraken`
2. `$ flatpak run --filesystem=xdg-run/gvfs --talk-name=org.gtk.vfs --talk-name=org.gtk.vfs.* com.axosoft.GitKraken`

Thanks !

**Comment by Eonfge** [comment]
I'll be unable to reproduce this case easily, as I've moved companies since I reported this issue. Might be able to reproduce it later, but no guarantees.

**Comment by magnum79** [comment]
I can confirm that. Snap version of GitKraken is unable to open repository in a folder, that mounted through sftp. I can see this folder in Files, and I cannot select this folder from GitKraken GUI.
Uninstalling Snap version and installing .deb verion solves the issue.
OS: Ubuntu 20.04

**Comment by Lctrs** [comment]
Hi @magnum79.

This is the repo of the unofficial flatpak wrapper for GitKraken. We are not affiliated in any way to Axosoft (GitKraken's editor). You can contact them on their [Slack](https://gitkraken.slack.com/).

**Comment by Eonfge** [comment]
I have a possible solution. GNOME 40 changed some of the permissions for gvsd so you'll have to add another permission.

```
"--filesystem=xdg-run/gvfsd",
```


I've seen this before with Lollypop:

https://github.com/flathub/org.gnome.Lollypop/pull/141

**Comment by Lctrs** [comment]
This has already been done.
