### ISSUE TITLE
Specifying a http proxy

### ISSUE THREAD

**Issue by CRCinAU** [flathub/com.axosoft.GitKraken#4]
We live behind a http proxy, and using flatpak, I can't seem to specify this any way.

Previously, I used: ~/bin/gitkraken/gitkraken --proxy=10.1.1.1:8000

Is there a way to do this via flatpak?

**Comment by Lctrs** [comment]
AFAIK, the only solution would be to launch it from the CLI and overriding the default command. Something like this : `flatpak run com.axosoft.GitKraken --command="/app/extra/gitkraken/gitkraken --proxy=10.1.1.1:8000"`
