### ISSUE TITLE
Unable to update git config

### ISSUE THREAD

**Issue by MarcAureleCoste** [flathub/com.axosoft.GitKraken#42]
I update Gitkraken, installed with flatpak and I get this error when I try to switch my profile

![2019-08-12_428x206_scrot](https://user-images.githubusercontent.com/4977822/62885213-90ff9d00-bd38-11e9-822c-811752201911.png)

But interestingly if I reload the window my profile is switched.
 
Does anybody have an idea on how to avoid/resolve this problem?

**Comment by Lctrs** [comment]
Is this file present when GK is closed ? If yes, delete it and retry your process in GK.

Sadly, I'm on the free version of GK so I won't be of good help. You can try to ask for help in their [Slack](https://gitkraken.slack.com/).

**Comment by MarcAureleCoste** [comment]
Removing the file **.gitconfig.lock** solve the problem.

Finally it was easy to solve.

Thanks
