### ISSUE TITLE
Can't connect to SSH_AGENT

### ISSUE THREAD

**Issue by CRCinAU** [flathub/com.axosoft.GitKraken#5]
It seems that the flatpak version of GK cannot use the SSH Agent for authentication.

Error message:
Fetch failed for 'origin'
error authenticating: failed connecting with agent

**Comment by Lctrs** [comment]
Hi !

Weird. I'm using SSH agent without any problem.

What OS are you using ? What is your flatpak version ? What SSH agent are you using ?

**Comment by CRCinAU** [comment]
I'm using Fedora 28 with KeePassXC as the SSH Agent.

Fedora 28 comes with Flatpak 0.11.8.2-1.fc28

**Comment by Lctrs** [comment]
Is KeepassXC running as a flatpak app ?

**Comment by TomAdam** [comment]
I get the same with the default agent

**Comment by Lctrs** [comment]
I reproduced the problem and can confirm it indeed doesn't work with any SSH Agent.

Sadly, it seems that we cannot fix on the application level. See https://github.com/flatpak/flatpak/issues/1438.

**Comment by Lctrs** [comment]
Good news. It'll be possible in the next flatpak version. See https://github.com/flatpak/flatpak/pull/1764.
