### ISSUE TITLE
GloBoard tab is not function

### ISSUE THREAD

**Issue by soliverr** [flathub/com.axosoft.GitKraken#50]
On my _Ubuntu_:

    $ lsb_release --all
    Distributor ID:	Ubuntu
    Description:	Ubuntu 18.04.1 LTS
    Release:	18.04
    Codename:	bionic

    GitKraken 6.3.0

GloBoard tab is just empty black space without any activity in it.

When I try to open GloBoard in official GitKraken deb-package, GloBoard works as normal.

How can I explore what's wrong with flathub package?

**Comment by Lctrs** [comment]
Hi and thanks for reporting this.

It's weird because it appears to work well on my machine (Fedora 30). I'm not using Glo myself but it loads.

Could you launch from the terminal (`flatpak run com.axosoft.GitKraken`), try to load Glo, and tells me if any error pops out in the terminal or in `Help > Support Logs > View Error Logs` please ?

**Comment by soliverr** [comment]
```
$ flatpak run com.axosoft.GitKraken
Gtk-Message: 10:02:53.851: Failed to load module "canberra-gtk-module"
Gtk-Message: 10:02:53.851: Failed to load module "canberra-gtk-module"
state:  update-not-available
state:  checking-for-update
state:  update-not-available
state:  checking-for-update
state:  update-not-available
...
```

Every time I refreshed _'Ctrl-r'_ Glo tab I got two lines about _state_. Nothing else.

There was no any errors in support logs too.

**Comment by Lctrs** [comment]
Weird. I just installed Ubuntu 18.04 in a VM on my machine, installed GK through flatpak and Glo also loads here...

Are you behind a corporate proxy ?

**Comment by Lctrs** [comment]
@soliverr any news ?

**Comment by soliverr** [comment]
Hi.

I've tested Glo board from my home PC (Ubuntu 19.10) and from my workplace (Ubuntu 18.04). In both cases deb-package's Glo board is function, but flatpak's Glo board is not.

I sniffed packets by wireshark and saw, that in case flatpak's Glo there was an error in transport layer while TLS/SSL handshake, and a connection process nas been stopped.

In case deb's Glo board I saw this error too, but connection process keept going further.

It is not seems that a proxy matters.

Now I try to figure out what is wrong with permissions in flatpak's package.

**Comment by Lctrs** [comment]
Hmm weird... Don't know what's going on here. Could be a bug in the Runtime but don't know...

cc @nedrichards @TingPing @barthalion. Any thoughts ?

**Comment by Lctrs** [comment]
What's the URL that triggers the error during TSL/SSL handshake ?

**Comment by Lctrs** [comment]
@soliverr Any news ?

**Comment by soliverr** [comment]
I and my colleague have checked flatpack's GitKraken under Arch Linux. GloBoard tab is not functional too.

Digging further...

**Comment by Lctrs** [comment]
Any news @soliverr ?

**Comment by soliverr** [comment]
Time heals all wounds, as they say. :)

```
$ lsb_release --all
LSB Version:	core-11.1.0ubuntu2-noarch:printing-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```

```
$ flatpak info com.axosoft.GitKraken

GitKraken - For repo management, in-app code editing & issue tracking.

              ID: com.axosoft.GitKraken
          Ссылка: app/com.axosoft.GitKraken/x86_64/stable
     Архитектура: x86_64
           Ветка: stable
          Версия: 7.4.1
         License: LicenseRef-proprietary
        Источник: flathub
       Коллекция: org.flathub.Stable
       Установка: user
      Установлен: 30,8 MB
Среда исполнения: org.gnome.Platform/x86_64/3.38
             Sdk: org.gnome.Sdk/x86_64/3.38
```

GloBoards became GitKrakenBoards. And it just works!

I had switched from deb-package to flatpak-package of GitKraken.
