### ISSUE TITLE
File -> Preferences menu does not open

### ISSUE THREAD

**Issue by CRCinAU** [flathub/com.axosoft.GitKraken#6]
Seems to work by hitting the stacked menu, then choosing Preferences - however choosing it from the File menu doesn't do anything.

**Comment by Lctrs** [comment]
I'm also on Fedora 28 and I do not have this problem.

Try to launch it from the CLI (`flatpak run com.axosoft.GitKraken`) and see if everything pop up in the CLI while trying to perform this action please.

**Comment by TomAdam** [comment]
Both work fine for me

**Comment by tim77** [comment]
Same issue.

- Fedora 32 Workstation (GNOME) [all updates installed]
- Xorg session
- NVIDIA GP106 [GeForce GTX 1060 6GB] driver: nvidia v: 455.28

App relaunching automatically after crash when trying to open Preferences. Output:

```
state:  update-not-available
state:  checking-for-update
(node:55) Electron: Loading non-context-aware native module in renderer: '/app/extra/gitkraken/resources/app.asar.unpacked/node_modules/@axosoft/nodegit/build/Release/nodegit-fedora-28.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:55) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:55) [DEP0106] DeprecationWarning: crypto.createDecipher is deprecated.
state:  update-not-available
Cannot upload crash dump: failed to open
--2020-10-24 14:24:27--  https://crash.gitkraken.com/submit
Resolving crash.gitkraken.com (crash.gitkraken.com)... 174.46.225.159
Connecting to crash.gitkraken.com (crash.gitkraken.com)|174.46.225.159|:443... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2020-10-24 14:24:28 ERROR 500: Internal Server Error.


Unexpected crash report id length
Failed to get crash dump id.
Report Id: 
state:  checking-for-update
(node:176) Electron: Loading non-context-aware native module in renderer: '/app/extra/gitkraken/resources/app.asar.unpacked/node_modules/@axosoft/nodegit/build/Release/nodegit-fedora-28.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:176) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:176) [DEP0106] DeprecationWarning: crypto.createDecipher is deprecated.
state:  update-not-available
```

**Comment by Lctrs** [comment]
Could you provide error log ? You can find it in the app under `Help > Support Logs > View Error Logs`

**Comment by tim77** [comment]
@Lctrs yep, i wanted to provide it from the beginning, but this is weirdness number 2 for for me since when i am trying to open `Help > Support Logs > View Error Logs` nothing happens. And nothing even happens in terminal output when this event.

**Comment by Lctrs** [comment]
Maybe you can manually find a log somewhere under `~/.var/app/com.axosoft.GitKraken`. I don't have a Linux under the hand right now so I can't lead you further...

**Comment by tim77** [comment]
Tried to find something useful in `~/.var/app/com.axosoft.GitKraken` and `~/.gitkraken` since we have `--filesystem=host` here and GitKraken seems like prefer to store his configuration in `~/.gitkraken` in this case but `error-log.txt` is empty file. Also tried to remove `--filesystem=host` completely but issue is still here. No luck yet. I'll try to provide more info which could help if there some in future.

**Comment by Lctrs** [comment]
Maybe you could also report to upstream on their [Slack ](https://gitkraken.slack.com/)? Though they'll probably tell you that they don't provide support for Flatpak since they don't support it.

@CRCinAU Do you have a nvidia gpu as well ?

**Comment by Lctrs** [comment]
@tim77 If you report it on their Slack, please also tell them that the automatic upload of the crash dump fails.

**Comment by tim77** [comment]
I've got some [coredump](https://atim.fedorapeople.org/gitkraken-dump.tar.xz), maybe this could help us:
```
❯ coredumpctl info /app/extra/gitkraken/gitkraken
           PID: 9988 (gitkraken)
           UID: 1000 (tim)
           GID: 1000 (tim)
        Signal: 11 (SEGV)
     Timestamp: Sat 2020-10-24 21:52:44 EEST (5min ago)
  Command Line: /app/extra/gitkraken/gitkraken --type=renderer --field-trial-handle=10801317837068408270,15813570506184202369,131072 --enable-features=WebComponentsV0Enabled --disable-features=SpareRendererF>
    Executable: /app/extra/gitkraken/gitkraken
 Control Group: /user.slice/user-1000.slice/user@1000.service/app-flatpak-com.axosoft.GitKraken-9909.scope
          Unit: user@1000.service
     User Unit: app-flatpak-com.axosoft.GitKraken-9909.scope
         Slice: user-1000.slice
     Owner UID: 1000 (tim)
       Boot ID: 292674331b5f49978284393d5b22d150
    Machine ID: e01ec3e7be494b558839c543a3a1aafc
      Hostname: pc
       Storage: /var/lib/systemd/coredump/core.gitkraken.1000.292674331b5f49978284393d5b22d150.9988.1603565564000000.lz4
       Message: Process 9988 (gitkraken) of user 1000 dumped core.
                
                Stack trace of thread 120:
                #0  0x00007f43eb6f0715 n/a (/usr/lib/x86_64-linux-gnu/libc-2.31.so + 0x161715)
                #1  0x00007f43ceec91b9 n/a (/app/extra/gitkraken/resources/app.asar.unpacked/node_modules/font-scanner/build/Release/fontmanager.node + 0x81b9)
                #2  0x00007f43ceec928b n/a (/app/extra/gitkraken/resources/app.asar.unpacked/node_modules/font-scanner/build/Release/fontmanager.node + 0x828b)
                #3  0x00007f43ceec41f8 n/a (/app/extra/gitkraken/resources/app.asar.unpacked/node_modules/font-scanner/build/Release/fontmanager.node + 0x31f8)
                #4  0x000055961e0aff7a n/a (/app/extra/gitkraken/gitkraken + 0x73c7f7a)
                #5  0x00007f43ecde14d2 n/a (/usr/lib/x86_64-linux-gnu/libpthread-2.31.so + 0x84d2)
```

And i'll try to report upstream :soon:

**Comment by Lctrs** [comment]
Congrats for getting a coredump @tim77 !

Can confirm I can't reproduce the issue on my side (F32 Silverblue, Wayland, Intel CPU (no nvidia nor amd gpu)).

**Comment by Lctrs** [comment]
@tim77 Can you reproduce the bug with the official rpm ?

**Comment by tim77** [comment]
Preferences menu works in RPM version, but i've tested in my `f32` guest VM. Didn't tested on this host machine.

**Comment by Lctrs** [comment]
Problem is on our side then. :/

My guess is that the problem is somewhat related to nvidia. Do you have the latest driver version (on the host and on flatpak) ?

What happen if you launch GK with `flatpak run --nodevice=dri com.axosoft.GitKraken` ?

**Comment by tim77** [comment]
> My guess is that the problem is somewhat related to nvidia.

+1. I've tried flatpak build in `f32` guest VM and it works fine, no issue.

> Do you have the latest driver version (on the host and on flatpak) ?

Definitely. Both updated and synced. Latest version.

> What happen if you launch GK with flatpak run --nodevice=dri com.axosoft.GitKraken ?

I would say with `--nodevice=dri` output is the same.

Most important: i can't reproduce this bug and flatpak build works on same machine. Nothing changed since these few days. Configuration and installation the same. No updates. It works. Magic. I've run it without `--filesystem=host`. But i've also tried before without `--filesystem=host` and experienced this issue though.

**Comment by Lctrs** [comment]
So, the issue resolved itself ?

**Comment by tim77** [comment]
At this moment yes. But i'll try play again with `--filesystem=host` and something make me think that this affect reproducibility of this bug. BTW do we really need `--filesystem=host` there? Maybe `home` and `/mnt` would be more then enough? What do you think? `--filesystem=host` is generally discouraged.

**Comment by Lctrs** [comment]
I agree.

**Comment by Lctrs** [comment]
@tim77 Please test #86.
