### ISSUE TITLE
Can't clone via SSH from a server with a ED25519 host key (OpenSSH 7.9), neither using SSH agent nor manually selecting a key

### ISSUE THREAD

**Issue by fanfan54** [flathub/com.axosoft.GitKraken#61]
Hello,

I encounter SSH auth problems with GitKraken 6.4.1, but only with the current stable flathub distribution, I have no problem using the version I installed with [the official RPM package provided by Axosoft](https://release.gitkraken.com/linux/gitkraken-amd64.rpm).
Strangely, this problem happens only on a specific git server from my university (available at `git.epitech.eu`, which runs `OpenSSH_7.9 FreeBSD-openssh-portable-7.9.p1_1,1` and only has a ED25519 server key and the `curve25519-sha256` key exchange algorithm), because I managed to clone private repos successfully on both GitKraken distributions (RPM and flatpak) from:
- GitHub, via HTTPS using the built-in integration in GitKraken, which uses OAuth to connect)
- GitHub, only via a SSH key from my host SSH agent (**Use local SSH agent** was enabled in GitKraken), but it has ED25519 + ECDSA + RSA server keys
- SourceForge, only via a SSH key from my host SSH agent (**Use local SSH agent** was enabled in GitKraken), but it has RSA server keys

... but not from my university's server :cry: 

I'm using Fedora 31 Workstation (64 bits), I was previously the RPM version of GitKraken 6.4.1, and I decided to reinstall it from the flathub stable branch (by typing `flatpak install flathub com.axosoft.GitKraken`). I have Flatpak 1.4.3 from the official Fedora repo.

When I try to **Clone with URL** any repository I have on `git.epitech.eu` (with the user `git@git.epitech.eu`), I have the following error:
![failed to start SSH session: Unable to exchange encryption keys](https://user-images.githubusercontent.com/11705441/71969397-da301c00-3206-11ea-833e-16ce9e8f7373.png)

### What I tried (and didn't work)
- Adding my private keys (which work when I use git from the command line on my host system) to my host SSH agent, and enabling **Use local SSH agent** in **Authentification > General** in GitKraken settings
- Disabling **Use local SSH agent** and manually adding the same key in **SSH Private Key** and **SSH Public Key** in GitKraken settings
- Generating new Private/Public keys in GitKraken settings (and, of course, uploading the new public key to my university's server)
- Launching GitKraken with ` --socket=ssh-auth` (as suggested by #5) and retrying the same steps
- Launching GitKraken with `--command=bash --share=network --filesystem=$SSH_AUTH_SOCK --env=SSH_AUTH_SOCK=$SSH_AUTH_SOCK` (as suggested by https://github.com/flatpak/flatpak/issues/1438) and retrying the same steps

## Infos from sshcheck.com about the servers I tried
- My university's server: https://sshcheck.com/server/git.epitech.eu
- SourceForge: https://sshcheck.com/server/git.code.sf.net
- GitHub: https://sshcheck.com/server/github.com

### GitKraken flatpak application log when trying to clone
```
[11:07:37] Detecting Git and Git LFS: started
[11:07:38] Detected Git: 2.23.0
[11:07:38] Detected Git LFS: 2.9.2
[11:07:38] Detecting Git and Git LFS: finished1.632s
[11:08:15] Clone repository ssh://git@git.epitech.eu/[redacted]/internship_2019 into /home/francois/internship_2019: started.
[11:08:15] Clone repository ssh://git@git.epitech.eu/[redacted]/internship_2019 into /home/francois/internship_2019: failed to start SSH session: Unable to exchange encryption keys
[11:08:15] Clone repository: finished with errors.
```

### ssh -v git@git.epitech.eu (my university's server)
```
OpenSSH_8.1p1, OpenSSL 1.1.1d FIPS  10 Sep 2019
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Reading configuration data /etc/ssh/ssh_config.d/05-redhat.conf
debug1: Reading configuration data /etc/crypto-policies/back-ends/openssh.config
debug1: configuration requests final Match pass
debug1: re-parsing configuration
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Reading configuration data /etc/ssh/ssh_config.d/05-redhat.conf
debug1: Reading configuration data /etc/crypto-policies/back-ends/openssh.config
debug1: Connecting to git.epitech.eu [163.5.42.53] port 22.
debug1: Connection established.
debug1: identity file /home/francois/.ssh/id_rsa type -1
debug1: identity file /home/francois/.ssh/id_rsa-cert type -1
debug1: identity file /home/francois/.ssh/id_dsa type -1
debug1: identity file /home/francois/.ssh/id_dsa-cert type -1
debug1: identity file /home/francois/.ssh/id_ecdsa type -1
debug1: identity file /home/francois/.ssh/id_ecdsa-cert type -1
debug1: identity file /home/francois/.ssh/id_ed25519 type -1
debug1: identity file /home/francois/.ssh/id_ed25519-cert type -1
debug1: identity file /home/francois/.ssh/id_xmss type -1
debug1: identity file /home/francois/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.1
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.9 FreeBSD-openssh-portable-7.9.p1_1,1
debug1: match: OpenSSH_7.9 FreeBSD-openssh-portable-7.9.p1_1,1 pat OpenSSH* compat 0x04000000
debug1: Authenticating to git.epitech.eu:22 as 'git'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ssh-ed25519
debug1: kex: server->client cipher: aes256-gcm@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: aes256-gcm@openssh.com MAC: <implicit> compression: none
debug1: kex: curve25519-sha256 need=32 dh_need=32
debug1: kex: curve25519-sha256 need=32 dh_need=32
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ssh-ed25519 SHA256:WnZatelotilt6A6Fj4GUAjd4vGY5P1wZag/UCa85ROY
debug1: Host 'git.epitech.eu' is known and matches the ED25519 host key.
debug1: Found key in /home/francois/.ssh/known_hosts:14
debug1: rekey out after 4294967296 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 4294967296 blocks
debug1: Will attempt key: [REDACTED]@ap20fedo-xps RSA SHA256:[REDACTED] agent
debug1: Will attempt key: /home/francois/.ssh/id_rsa 
debug1: Will attempt key: /home/francois/.ssh/id_dsa 
debug1: Will attempt key: /home/francois/.ssh/id_ecdsa 
debug1: Will attempt key: /home/francois/.ssh/id_ed25519 
debug1: Will attempt key: /home/francois/.ssh/id_xmss 
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering public key: [REDACTED]@ap20fedo-xps RSA SHA256:[REDACTED] agent
debug1: Server accepts key: [REDACTED]@ap20fedo-xps RSA SHA256:[REDACTED] agent
debug1: Authentication succeeded (publickey).
Authenticated to git.epitech.eu ([163.5.42.53]:22).
debug1: channel 0: new [client-session]
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
debug1: pledge: network
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
debug1: Remote: /usr/local/bin/boss_get_sshkey %u %f:2: key options: agent-forwarding command port-forwarding user-rc x11-forwarding
debug1: Remote: /usr/local/bin/boss_get_sshkey %u %f:5: key options: agent-forwarding command port-forwarding user-rc x11-forwarding
debug1: Sending environment.
debug1: Sending env LANGUAGE = en_US.utf8
debug1: Sending env XMODIFIERS = @im=none
debug1: Sending env LANG = fr_FR.utf8
PTY allocation request failed on channel 0

Hi [REDACTED]! You've successfully authenticated,
but I do not provide interactive shell access.

debug1: client_input_channel_req: channel 0 rtype exit-status reply 0
debug1: client_input_channel_req: channel 0 rtype eow@openssh.com reply 0
debug1: channel 0: free: client-session, nchannels 1
Connection to git.epitech.eu closed.
Transferred: sent 3220, received 2484 bytes, in 0.5 seconds
Bytes per second: sent 6325.7, received 4879.8
debug1: Exit status 128
```

Can someone help me? Thanks!
I'll use the RPM version of GitKraken in the meantime :eyes:

**Comment by Lctrs** [comment]
Hi @fanfan54,

Sorry for the late reply. I haven't had the time to dig it further but I must admit I'm a little clueless on this one.

May you test the new version (`6.5.0`) that came out yesterday and tell me if it fixed your issue ?

**Comment by fanfan54** [comment]
Hi,

(also) sorry for the late reply, I can confirm you that it still doesn't work with the flatpak release version `6.5.0` :confused:

**Comment by Lctrs** [comment]
Any news @fanfan54 ?
