### ISSUE TITLE
No GPG smartcard found

### ISSUE THREAD

**Issue by wmutschl** [flathub/com.axosoft.GitKraken#67]
I recently switched from Ubuntu to Manjaro and installed the flatpak version of Gitkraken. Everything works fine, but I am not able to use my Yubikey as SmartCard for the private GPG key in the app. I am able to view my signing key in the settings, but using my Yubikey for the private key yields an error "no gpg smartcard found". See this gif:
![FLATPAK_working_gpg_but_no_smartcard](https://user-images.githubusercontent.com/36013296/76164265-c55ffe00-614d-11ea-8896-bbfd6e31355c.gif)

  
When I install Gitkraken through the AUR, everything works fine. I am able to use my private keys from my gpg card (Yubikey). I attach a gif how it works (and how it used to work in Ubuntu for me):
![AUR_working_gpg_and_smartcard](https://user-images.githubusercontent.com/36013296/76164201-49fe4c80-614d-11ea-9dba-c7ca9c40a999.gif)

Thank you for this app and any suggestion!

**Comment by Lctrs** [comment]
Does `flatpak run --device=all com.axosoft.GitKraken` fix your problem ?

**Comment by wmutschl** [comment]
Unfortunately not.

**Comment by Lctrs** [comment]
I don't have a YubiKey myself. So I'll need you to test things if you're okay with this.

Can you try #68 and tells me if it works for you ?

**Comment by wmutschl** [comment]
Yes this works for me, thank you! Do you need any other things to be tested? Can I somehow support your work/this project?

**Comment by Lctrs** [comment]
@wmutschl Nope, just wanted you to confirm that #68 fixed your problem. Thanks for the input. Don't hesitate to open new issues if you find some.

And no, there is no way to support my work. But thanks for the proposal anyway.
