### ISSUE TITLE
Cannot run in Linux Mint 18.3

### ISSUE THREAD

**Issue by herdibintang** [flathub/com.axosoft.GitKraken#8]
Command `flatpak run com.axosoft.GitKraken` returning `error: Unknown socket type ssh-auth, valid types are: x11, wayland, pulseaudio, session-bus, system-bus`

**Comment by Lctrs** [comment]
The minimum flatpak version compatible with our wrapper is Flatpak 0.11.1.

What is your flatpak version ?

**Comment by herdibintang** [comment]
Thank you for your reply.

Preinstalled version is `0.10.0`. Updating `flatpak` version fix this problem. This [link](https://forums.linuxmint.com/viewtopic.php?t=265231) tells how if anybody wondering.
