### ISSUE TITLE
LFS Support

### ISSUE THREAD

**Issue by TheFlagCourier** [flathub/com.axosoft.GitKraken#9]
Current Flatpak does not detect if the Git Large File Storage extension is installed, and will throw a warning if it finds a repository using LFS.
(Stored at `/usr/bin/git-lfs`)

**Comment by nedrichards** [comment]
So, sparkleshare adds git-lfs like this https://github.com/flathub/org.sparkleshare.SparkleShare/blob/cd889bb8628a261b2c099e652c24f9c2766f6f5b/org.sparkleshare.SparkleShare.json#L52 (maybe a few tweaks needed) but that'd be at /app/bin/git-lfs so you might need to do something like use `ensure-writable` and then do a symlink in a `post-install` block or something.

It should be totally doable though.

**Comment by Lctrs** [comment]
Close in https://github.com/flathub/com.axosoft.GitKraken/commit/d6ef9a43732577e87a59a26ee4e677a1c03acc71.
